### ISSUE TITLE
Option to hide grade from views

### ISSUE THREAD

**Issue by mysticuno** [popoffka/lmoddiff#2]
Sometimes I'm browsing and I have friends around and I just want to check what the new assignments are. I might have bombed the last pset, but I might not want to reveal what my actual score was. It'd be nice if there were an option to hide the grades from the view such that I would only see the assignment (and previous assignments) sans the grade, maybe with just a ✔️ or ❌ or ❔  indicating whether the assignment was graded/if I actually submitted something for it.

**Comment by aleksejspopovs** [comment]
Makes sense.

So, do you think a checkbox like “Show grades” next to “Auto-sync” and “Show notifications”, on by default, would be a good solution?

**Comment by mysticuno** [comment]
Seems simple enough for now and I think that would adequately get the job
done.

**Comment by aleksejspopovs** [comment]
@mysticuno done! I have published the update on Webstore, the extension should auto-update in a couple of hours.
